## Minimal, networked, SSH-reachable base for vm-03's NixOS conversion
## (2026-07-24). Same shape as srv-01/gpu-02.
##
## vm-03 is a Hyper-V VM on `hyperv-host` (amd64, 4 vCPU / 3.8G RAM, one 40G
## virtual disk). Its only role was being a k3s agent; it was drained and
## removed from the cluster before this conversion and its workloads
## (labodeludo/gh-runner, netalertx) already live on gpu-01. **k3s membership
## is deliberately NOT re-declared here** - rejoining the cluster is a
## separate follow-up, not a silent drop.
##
## Also deliberately not carried over (follow-up, see the preserved tarball
## at gpu-01:~/vm-03-preserve/): the Cronicle-driven S3 backup, i.e.
## ~/scripts/homelab-backup.sh, the ~/.ssh/homelab_backup_kp KeePass-fetch
## key, and the forced-command `cronicle-backup-vm-03` authorized_keys
## entry. Its Kuma push monitor will go down until that is re-provisioned
## or retired.
##
## hardware-configuration.nix (imported below) carries the initrd storage
## modules - omitting those is what made srv-01's first install
## unbootable, so it is generated by nixos-anywhere and imported from the
## start.
##
## Networking: unlike srv-01/gpu-02 there is NO VLAN tagging to do
## here. Hyper-V hands the guest two already-untagged synthetic NICs, one
## per vswitch - eth0 on VLAN10, eth1 on VLAN50. Both are matched by MAC
## rather than by name so the config does not depend on how systemd ends
## up naming vmbus interfaces.
{ ... }:
{
  imports = [ ./hardware-configuration.nix ../../modules/k3s-agent.nix ../../modules/private-ca.nix ];
  services.k3s.extraFlags = [ "--node-ip=192.0.2.135" ];

  networking.hostName = "vm-03";
  networking.useNetworkd = true;
  networking.useDHCP = false;

  # NB: virtualisation.hypervGuest.enable is set by the generated
  # hardware-configuration.nix (nixos-generate-config detects Hyper-V), and
  # that is what pulls hv_storvsc/hv_netvsc into the initrd - so it is not
  # repeated here.

  systemd.network = {
    enable = true;

    # VLAN10 - primary, carries the default route (v4 static, v6 static
    # address + RA-learned default, matching the old Debian setup).
    networks."10-vlan10" = {
      matchConfig.MACAddress = "02:00:00:00:00:01";
      address = [
        "192.0.2.135/23"
        "2001:db8:50:a::87/64"
      ];
      routes = [ { Gateway = "192.0.2.254"; } ];
      networkConfig = {
        DNS = "192.0.2.254";
        IPv6AcceptRA = true;
      };
      # "~." makes pfSense's Unbound the resolver for *everything*, which is
      # what the old Debian resolv.conf did. Without it systemd-resolved
      # happily sends queries to its built-in fallback servers (1.1.1.1 &
      # co.), which cannot resolve the internal lab.example zone - public names
      # worked, every homelab name came back NXDOMAIN.
      domains = [ "lab.example" "example.com" "~." ];
    };

    # VLAN50 - secondary, no default route (same as the Debian config).
    networks."20-vlan50" = {
      matchConfig.MACAddress = "02:00:00:00:00:01";
      address = [ "203.0.113.135/23" ];
      networkConfig.DHCP = "no";
      linkConfig.RequiredForOnline = "no";
    };
  };
  networking.search = [ "lab.example" "example.com" ];

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  users.users.ludorl82 = {
    isNormalUser = true;
    extraGroups = [ "wheel" ];
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDUMMYDUMMYDUMMYDUMMYDUMMYDUMMYDUMMYDUMMY0000 reader@example"
      # gpu-01 is the fleet's build/deploy host; this is the key it uses for
      # nixos-anywhere and for `nixos-rebuild --target-host`. srv-01 and
      # gpu-02 predate this and still only carry the workstation key, so
      # they cannot be rebuilt remotely yet - worth backfilling there.
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDUMMYDUMMYDUMMYDUMMYDUMMYDUMMYDUMMYDUMMY0000 reader@example"
    ];
  };
  security.sudo.wheelNeedsPassword = false;

  services.openssh.enable = true;

  system.stateVersion = "26.05";
}
