## NixOS config for gaming-01 — Supermicro X11SRA-RF, same board as gpu-01.
## Converted from Windows 11 + Hyper-V (see net-cfgs/history.md).
##
## ROLE: gaming host AND an on-demand k3s node. The gaming guests (arcade1
## with the RTX 3060, arcade2 with a spare RTX 3050 once it is installed) run
## as libvirt VMs here, but gaming is rare and exclusive — so rather than let a
## 6-core/46 GB Xeon sit idle 99% of the time, gaming-01 ALSO joins the k3s
## cluster and does cluster work whenever nobody is playing.
##
## HOW THE TWO ROLES COEXIST (revised 2026-08-17 — this host used to be
## deliberately NOT a k3s node): the arcade VMs do NOT autostart. Starting them
## goes through a "game mode" flow (a Home Assistant button / the game-mode
## script) that CORDONS + DRAINS gaming-01 first, so k3s pods reschedule off it
## before the VM grabs the RAM/CPU — and UNCORDONS when the VM shuts down. Net
## effect: gaming-01 is ~100% k3s when idle and ~100% gaming when playing, with
## no reservation waste and no OOM from k3s + a VM fighting for the same RAM.
## The scheduler is NOT told to avoid this node (no taint) — the drain is what
## protects a gaming session, so a taint would only waste the idle capacity.
##
## The 3060 stays vfio-bound for passthrough (so k3s does not use the GPU); the
## reclaimed resource here is CPU + RAM. gpu-01 keeps the assistant backend
## (ollama) on its own GPU, so gaming-01's card is free to be gaming-only.
##
## hardware-configuration.nix is generated by nixos-anywhere on the booted
## installer and imported here. Omitting it (initrd storage modules) is
## what made srv-01's first install unbootable.
{ config, lib, pkgs, ... }:
let
  # Locked-down entrypoint for Home Assistant to turn the gaming VMs on/off.
  # HA's forced-command SSH key can ONLY run this — it reads the fixed command
  # from $SSH_ORIGINAL_COMMAND and permits nothing but start/stop/status of the
  # two arcade VMs. ludorl82 is in the libvirtd group, so `virsh` needs no sudo.
  # stop uses --mode agent because the guest's GNOME ignores the ACPI power
  # button; the qemu-guest-agent runs a clean poweroff instead.
  arcadeCtl = pkgs.writeShellScript "arcade-ctl" ''
    export PATH=/run/current-system/sw/bin:$PATH
    set -- $SSH_ORIGINAL_COMMAND
    action="$1"; vm="$2"
    case "$vm" in arcade1|arcade2) ;; *) echo "denied: bad vm"; exit 1 ;; esac
    case "$action" in
      start)  exec virsh -c qemu:///system start "$vm" ;;
      stop)   exec virsh -c qemu:///system shutdown --mode agent "$vm" ;;
      status) exec virsh -c qemu:///system domstate "$vm" ;;
      *) echo "denied: bad action"; exit 1 ;;
    esac
  '';
in
{
  imports = [
    ./hardware-configuration.nix
    ../../modules/private-ca.nix
    # On-demand k3s agent (see the header). Contributes CPU/RAM to the cluster
    # while the arcade VMs are shut down; drained before a gaming session.
    ../../modules/k3s-agent.nix
    # Replaces the old PowerShell NUT client at C:\Scripts\nut-monitor.ps1.
    # gaming-01 is on the rolling rack's CyberPower LX1500GU, whose USB cable
    # goes into gpu-01 — so gaming-01 is an upsmon SECONDARY of gpu-01, exactly like
    # gpu-02 and srv-01. POST-INSTALL STEP: seed
    # /var/lib/nut/monclient-password byte-identically to gpu-01's copy, or
    # upsmon refuses to start (which is the failure mode we want).
    ../../modules/ups-client.nix
  ];

  # GRUB, not systemd-boot, and installed for BOTH firmware modes on purpose.
  # gaming-01 is being converted with its firmware stuck in legacy/CSM mode
  # (Load Optimized Defaults on 2026-08-17 flipped it, and BIOS Setup is
  # unreachable — GPU owns video, AMI Setup does not render over SOL). The
  # booted installer confirmed legacy (/sys/firmware/efi absent). Which mode
  # the firmware is in cannot be seen or changed remotely, so the installed
  # system must boot either way:
  #   - device set to the real disk → GRUB embeds core.img in the EF02
  #     bios_grub partition (disko-config.nix) for the legacy/CSM path;
  #   - efiSupport + efiInstallAsRemovable → GRUB also writes the UEFI loader
  #     to the ESP's removable fallback (EFI/BOOT/BOOTX64.EFI), which the
  #     firmware boots WITHOUT an NVRAM entry — important because NVRAM boot
  #     vars are unwritable from a legacy-booted installer (no efivars) and
  #     Load Optimized Defaults likely cleared them anyway.
  # canTouchEfiVariables MUST be false with efiInstallAsRemovable.
  # REVISIT once the firmware is put back to UEFI on a physical visit: this
  # can revert to plain systemd-boot like gpu-01, though there is no need to.
  boot.loader.systemd-boot.enable = false;
  boot.loader.grub = {
    enable = true;
    efiSupport = true;
    efiInstallAsRemovable = true;
    device = "/dev/disk/by-id/nvme-EXAMPLE_NVME_0000000000000001";
    # Mirror the GRUB menu onto the BMC's SOL port (serial unit 1 = COM2, the
    # port the installer's POST output proved is bridged to SOL). This host is
    # headless — the onboard VGA is disabled in BIOS — so without this a failed
    # boot after the vfio change could not be recovered: there would be no way
    # to pick the previous generation. With it, `ipmitool ... sol activate`
    # shows the menu. --append keeps the graphical terminal too.
    extraConfig = ''
      serial --unit=1 --speed=115200 --word=8 --parity=no --stop=1
      terminal_input --append serial
      terminal_output --append serial
    '';
  };
  # Give the menu enough time to catch over a serial link before it auto-boots
  # the (default = newest) generation.
  boot.loader.timeout = lib.mkForce 8;
  boot.loader.efi.canTouchEfiVariables = false;
  boot.loader.efi.efiSysMountPoint = "/boot";

  # IOMMU + VFIO. IOMMU group 3 was verified to hold ONLY the RTX 3060
  # (0000:65:00.0, 10de:2503) and its HDMI-audio function (0000:65:00.1,
  # 10de:228e) — clean isolation, no ACS override needed. vfio-pci.ids binds
  # both at initrd time (vfio_pci is in boot.initrd.kernelModules below), so
  # nouveau never touches the card. NB the GPU id is 2503, NOT the 2504 an
  # earlier comment guessed — read off the live host.
  #
  # console=ttyS1: this host is HEADLESS. The onboard ASPEED VGA is disabled
  # in BIOS (not enumerated on the PCI bus — confirmed 2026-08-17), so once
  # the 3060 goes to vfio there is no local framebuffer and iKVM stays black
  # until a physical BIOS visit sets Primary Display=Onboard. A serial console
  # on the BMC's SOL port (ttyS1) is the stand-in: unlike AMI Setup, a Linux
  # serial console renders fully over SOL, so `ipmitool ... sol activate`
  # gives a real login. NixOS auto-starts serial-getty@ttyS1 from this param.
  boot.kernelParams = [
    "intel_iommu=on" "iommu=pt"
    "vfio-pci.ids=10de:2503,10de:228e"
    "console=tty0" "console=ttyS1,115200n8"
  ];

  networking.hostName = "gaming-01";
  networking.useNetworkd = true;
  networking.useDHCP = false;

  # Networking mirrors gpu-01's exactly, including the macvlan indirection.
  # WHY THE MACVLANS: this is a libvirt host, and any future guest that takes
  # a macvtap on the uplink (the gaming guests, most likely) cannot reach the
  # host stack over its own parent interface — a kernel property, not a
  # firewall or routing bug. So gaming-01's own addresses live on macvlans over
  # the parents rather than on the parents themselves, pre-emptively, exactly
  # as gpu-01 and srv-01 do (they learned it the hard way). The fix is needed
  # once per parent interface a guest has a macvtap on, hence both sides.
  # (This was originally set up for vm-03's return as a guest; vm-03 has
  # since been dropped from the fleet, but the pattern stands for the gaming
  # guests and the host already depends on these addresses, so it stays.)
  systemd.network = {
    enable = true;

    netdevs."10-vlan10" = {
      netdevConfig = { Name = "vlan10"; Kind = "vlan"; };
      vlanConfig.Id = 10;
    };
    netdevs."15-mvhost" = {
      netdevConfig = { Name = "mvhost"; Kind = "macvlan"; };
      macvlanConfig.Mode = "bridge";
    };
    netdevs."16-mvhost50" = {
      netdevConfig = { Name = "mvhost50"; Kind = "macvlan"; };
      macvlanConfig.Mode = "bridge";
    };

    # Untagged = VLAN50, tagged VLAN10 rides on top. NB: the interface name
    # is gpu-01's; if the install shows gaming-01 naming its uplink differently,
    # this is the one line to correct.
    networks."10-eno2" = {
      matchConfig.Name = "eno2";
      vlan = [ "vlan10" ];
      macvlan = [ "mvhost50" ];
      networkConfig.DHCP = "no";
      linkConfig.RequiredForOnline = "no";
    };
    # VLAN50 address: address ONLY, deliberately no gateway. The dual-homing
    # rule — exactly one default route per host and it is always the VLAN10
    # one. Two default routes is the most-repeated bug class in this lab.
    networks."25-mvhost50" = {
      matchConfig.Name = "mvhost50";
      address = [ "203.0.113.140/23" ];
      networkConfig.DHCP = "no";
      linkConfig.RequiredForOnline = "no";
    };
    # vlan10 parents the macvlan and brings the link up — no IP here.
    networks."20-vlan10" = {
      matchConfig.Name = "vlan10";
      macvlan = [ "mvhost" ];
      networkConfig.DHCP = "no";
      linkConfig.RequiredForOnline = "no";
    };
    # The real host address. hex(140) = 0x8c, per the VLAN10 IPv6 convention.
    networks."30-mvhost" = {
      matchConfig.Name = "mvhost";
      address = [
        "192.0.2.140/23"
        "2001:db8:50:a::8c/64"
      ];
      routes = [ { Gateway = "192.0.2.254"; } ];
      networkConfig = { DHCP = "no"; DNS = "192.0.2.254"; IPv6AcceptRA = true; };
      domains = [ "lab.example" "example.com" "~." ];
    };
  };
  networking.search = [ "lab.example" "example.com" ];

  # k3s agent: advertise the VLAN10 address as the node IP, same as every other
  # host (the module handles server address, token, firewall). No node taint —
  # the game-mode drain, not the scheduler, is what keeps a gaming session
  # clear of pods.
  services.k3s.extraFlags = [ "--node-ip=192.0.2.140" ];

  # GAME MODE: automatically drain gaming-01 off k3s while a gaming VM runs, and
  # return it to the pool when none is. This is a libvirt qemu hook, so it
  # fires no matter HOW the VM is started (Home Assistant button, `virsh
  # start`, autostart) — the on/off surface stays a dumb start/stop.
  #   - prepare (before the VM grabs RAM): cordon + drain gaming-01, so k3s pods
  #     move off it first and can't OOM against the 16 GB guest. Fast today
  #     since gaming-01 only carries DaemonSets (nothing evictable), but stays
  #     correct if the scheduler ever packs it.
  #   - release (VM stopped): if no OTHER arcade VM is still running, uncordon.
  # Uses the seeded admin kubeconfig. Re-entrancy-safe: it checks for the other
  # guest via pgrep, never by calling back into libvirt from inside the hook.
  virtualisation.libvirtd.hooks.qemu.gamemode = pkgs.writeShellScript "gamemode-qemu-hook" ''
    export PATH=/run/current-system/sw/bin:$PATH
    GUEST="$1"; OP="$2"
    case "$GUEST" in arcade1|arcade2) ;; *) exit 0 ;; esac
    K="k3s kubectl --kubeconfig=/etc/rancher/k3s/admin.yaml"
    OTHER=$([ "$GUEST" = arcade1 ] && echo arcade2 || echo arcade1)
    case "$OP" in
      prepare)
        logger -t gamemode "$GUEST starting -> cordon+drain gaming-01"
        $K cordon gaming-01 2>&1 | logger -t gamemode
        $K drain gaming-01 --ignore-daemonsets --delete-emptydir-data --force --timeout=120s 2>&1 | logger -t gamemode
        ;;
      release)
        if ! pgrep -f "guest=$OTHER," >/dev/null 2>&1; then
          logger -t gamemode "$GUEST stopped, no arcade running -> uncordon gaming-01"
          $K uncordon gaming-01 2>&1 | logger -t gamemode
        fi
        ;;
    esac
    exit 0
  '';

  users.users.ludorl82 = {
    isNormalUser = true;
    extraGroups = [ "wheel" "libvirtd" ];
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDUMMYDUMMYDUMMYDUMMYDUMMYDUMMYDUMMYDUMMY0000 reader@example"
      # Home Assistant's arcade on/off key — forced to arcadeCtl, nothing else.
      ''command="${arcadeCtl}",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDUMMYDUMMYDUMMYDUMMYDUMMYDUMMYDUMMYDUMMY0000 reader@example''
    ];
  };
  security.sudo.wheelNeedsPassword = false;
  services.openssh.enable = true;

  # libvirt/qemu-kvm host: the gaming guests land here once the second GPU
  # moves across. OVMF/UEFI firmware ships by default, which the Windows
  # guests will need. NOTE: on this host the virt-secret encryption key must
  # be created with the systemd HOST key, not the TPM — Load Optimized
  # Defaults (2026-08-17) left the onboard TPM2 throwing on Esys_CreatePrimary,
  # so `virt-secret-init-encryption` (which uses --with-key=auto → TPM first)
  # SIGABRTs under its sandbox on a fresh key. The key was seeded by hand with
  # --with-key=host during the install; if it is ever regenerated, do the same
  # until the TPM is cleared/re-enabled on a physical BIOS visit.
  virtualisation.libvirtd.enable = true;

  # NO NVIDIA DRIVER, ON PURPOSE: the 3060 goes to vfio-pci for passthrough
  # (bound via vfio-pci.ids in boot.kernelParams above), and a host nvidia/
  # nouveau driver would only have to be undone. nouveau is blacklisted so it
  # can never race vfio for the card at boot. There is no other GPU on this
  # host (the onboard ASPEED is disabled in BIOS), so blacklisting nouveau
  # outright costs nothing.
  #
  # Binding by `ids=` (not per-PCI-address driver_override) is deliberate: it
  # is unambiguous with one card today, and when the second GA106 3060 moves
  # across it will match that one too — exactly what the two-gaming-VMs layout
  # wants, no per-slot dance. If the second card turns out to report a
  # different device id, add it to the ids= list.
  boot.initrd.kernelModules = [ "vfio_pci" "vfio" "vfio_iommu_type1" ];
  boot.blacklistedKernelModules = [ "nouveau" ];

  # --- LAN/VPN-only VNC access to the arcade VMs ----------------------------
  # Each VM's QEMU VNC lives on gaming-01's localhost with a DYNAMIC display
  # (arcade1 was :0, arcade2 :1). These socket-activated proxies expose them on
  # gaming-01's LAN IP at FIXED ports (arcade1 -> 5901, arcade2 -> 5902) and
  # resolve the live display PER CONNECTION, so a VM restart — these are
  # on-demand — never leaves a stale port. Reachable as gaming-01.lab.example:5901
  # / :5902; the guests also forward their own :5900 here so
  # arcade{1,2}.lab.example:5900 work too. The firewall (below) limits the source
  # to the LAN (VLAN10/50) + WireGuard, IPv4 only — these private addresses are
  # already unreachable from the internet, this is defence in depth.
  systemd.sockets.arcade1-vncproxy = {
    wantedBy = [ "sockets.target" ];
    socketConfig = { ListenStream = "192.0.2.140:5901"; Accept = true; FreeBind = true; };
  };
  systemd.sockets.arcade2-vncproxy = {
    wantedBy = [ "sockets.target" ];
    socketConfig = { ListenStream = "192.0.2.140:5902"; Accept = true; FreeBind = true; };
  };
  systemd.services."arcade1-vncproxy@".serviceConfig = {
    ExecStart = pkgs.writeShellScript "arcade1-vncproxy" ''
      d=$(${pkgs.libvirt}/bin/virsh -c qemu:///system vncdisplay arcade1 2>/dev/null | ${pkgs.gnused}/bin/sed 's/.*://')
      [ -n "$d" ] || exit 1
      exec ${pkgs.socat}/bin/socat - TCP4:127.0.0.1:$((5900 + d))
    '';
    StandardInput = "socket";
    StandardOutput = "socket";
  };
  systemd.services."arcade2-vncproxy@".serviceConfig = {
    ExecStart = pkgs.writeShellScript "arcade2-vncproxy" ''
      d=$(${pkgs.libvirt}/bin/virsh -c qemu:///system vncdisplay arcade2 2>/dev/null | ${pkgs.gnused}/bin/sed 's/.*://')
      [ -n "$d" ] || exit 1
      exec ${pkgs.socat}/bin/socat - TCP4:127.0.0.1:$((5900 + d))
    '';
    StandardInput = "socket";
    StandardOutput = "socket";
  };
  networking.firewall.extraCommands = ''
    # arcade VNC proxies: LAN (VLAN10/50) + VPN (WireGuard + IPsec mobile)
    # sources only, IPv4.
    for net in 192.0.2.0/23 203.0.113.0/23 198.18.0.0/24 198.18.1.0/24; do
      iptables -A nixos-fw -p tcp -s "$net" --dport 5901 -j nixos-fw-accept
      iptables -A nixos-fw -p tcp -s "$net" --dport 5902 -j nixos-fw-accept
    done
  '';

  system.stateVersion = "26.05";
}
