## NixOS config for gaming-01 — Supermicro X11SRA-RF, same board as gpu-01.
## Converted from Windows 11 + Hyper-V (see net-cfgs/history.md).
##
## ROLE: gaming host AND an on-demand k3s node. The gaming guests (arcade1 and
## arcade2, one RTX 3050 each since 2026-09-14) run
## as libvirt VMs here, but gaming is rare and exclusive — so rather than let a
## 6-core/46 GB Xeon sit idle 99% of the time, gaming-01 ALSO joins the k3s
## cluster and does cluster work whenever nobody is playing.
##
## HOW THE TWO ROLES COEXIST (revised 2026-08-17 — this host used to be
## deliberately NOT a k3s node): the arcade VMs do NOT autostart. Starting them
## goes through a "game mode" flow (a Home Assistant button / the game-mode
## script) that CORDONS + DRAINS gaming-01 first, so k3s pods reschedule off it
## before the VM grabs the RAM/CPU — and UNCORDONS when the VM shuts down. Net
## effect: gaming-01 is ~100% k3s when idle and ~100% gaming when playing, with
## no reservation waste and no OOM from k3s + a VM fighting for the same RAM.
## The scheduler is NOT told to avoid this node (no taint) — the drain is what
## protects a gaming session, so a taint would only waste the idle capacity.
##
## THREE GPUs since 2026-09-14. The two RTX 3050s stay vfio-bound for
## passthrough and are invisible to the kubelet — gaming only. The GTX 960 is
## neither passed through nor usable: giving it to the host for k3s was tried
## and REVERTED the same day (kernel deadlock — see the GPU block below), so it
## sits unbound. The reclaimed resource here remains CPU + RAM only.
##
## hardware-configuration.nix is generated by nixos-anywhere on the booted
## installer and imported here. Omitting it (initrd storage modules) is
## what made srv-01's first install unbootable.
{ config, lib, pkgs, ... }:
let
  # Stops vm-03 (the GPU node) before a gaming session. Run detached by the
  # game-mode hook via systemd-run, never inline — see the hook for why.
  # Clean shutdown through the guest agent first, because vm-03 is a k3s node
  # and yanking it leaves pods to time out; destroy only if the agent will not
  # take it within a minute.
  stopWorker5 = pkgs.writeShellScript "gamemode-stop-vm-03" ''
    export PATH=/run/current-system/sw/bin:$PATH
    virsh domstate vm-03 2>/dev/null | grep -q running || exit 0
    logger -t gamemode "stopping vm-03 for a gaming session"
    virsh shutdown vm-03 --mode agent 2>&1 | logger -t gamemode
    for _ in $(seq 30); do
      virsh domstate vm-03 2>/dev/null | grep -q "shut off" && exit 0
      sleep 2
    done
    logger -t gamemode "vm-03 ignored the agent shutdown, destroying"
    virsh destroy vm-03 2>&1 | logger -t gamemode
  '';

  # Locked-down entrypoint for Home Assistant to turn the gaming VMs on/off.
  # HA's forced-command SSH key can ONLY run this — it reads the fixed command
  # from $SSH_ORIGINAL_COMMAND and permits nothing but start/stop/status of the
  # two arcade VMs. ludorl82 is in the libvirtd group, so `virsh` needs no sudo.
  # stop uses --mode agent because the guest's GNOME ignores the ACPI power
  # button; the qemu-guest-agent runs a clean poweroff instead.
  arcadeCtl = pkgs.writeShellScript "arcade-ctl" ''
    # /run/wrappers/bin FIRST: that is where NixOS keeps the only setuid sudo.
    # Putting /run/current-system/sw/bin ahead of it shadowed it with the
    # store's non-setuid sudo — "must be owned by uid 0 and have the setuid
    # bit set" — and the vm-03 drain silently failed again (2026-09-15).
    export PATH=/run/wrappers/bin:/run/current-system/sw/bin:$PATH
    V="virsh -c qemu:///system"
    set -- $SSH_ORIGINAL_COMMAND
    action="$1"; vm="$2"
    case "$vm" in arcade1|arcade2) ;; *) echo "denied: bad vm"; exit 1 ;; esac

    # vm-03 holds ALL THREE GPUs while nobody is playing, so it must let go
    # of the arcade card BEFORE the guest starts, or libvirt refuses the domain
    # with the device already in use.
    #
    # THIS is where that wait belongs, not in the libvirt qemu hook. This script
    # runs in ordinary userspace (an SSH forced command from Home Assistant), so
    # it can block on virsh safely. The hook cannot: it executes while libvirtd
    # holds locks for the domain being started, and calling back into libvirtd
    # from there can deadlock — which is why the hook only fires a best-effort
    # asynchronous stop, as a safety net for a `virsh start` typed by hand.
    #
    # Bringing vm-03 BACK is not done here: the guest is still shutting down
    # when `shutdown` returns, so this script could never see the right moment.
    # The libvirt hook's `release` branch does it, once the guest has actually
    # stopped and only if no other arcade guest is left running.
    stop_worker5() {
      $V domstate vm-03 2>/dev/null | grep -q running || return 0
      echo "stopping vm-03 to free its GPUs"
      # sudo -n: this runs as ludorl82 (HA's forced command) and the kubeconfig
      # is root-only — without it the drain fails with permission denied and
      # pods get killed by the shutdown instead of evicted (seen 2026-09-15).
      sudo -n k3s kubectl --kubeconfig=/etc/rancher/k3s/admin.yaml \
        drain vm-03 --ignore-daemonsets --delete-emptydir-data --force --timeout=60s 2>&1 | tail -1
      $V shutdown vm-03 --mode agent >/dev/null 2>&1
      for _ in $(seq 45); do
        $V domstate vm-03 2>/dev/null | grep -q "shut off" && return 0
        sleep 2
      done
      echo "vm-03 ignored the agent shutdown, destroying"
      $V destroy vm-03 >/dev/null 2>&1
      sleep 2
    }


    case "$action" in
      start)  stop_worker5; exec $V start "$vm" ;;
      stop)
        # PATIENT on purpose. The shutdown goes through the qemu guest agent
        # (the desktop ignores ACPI), and the agent takes ~30-60s to come up
        # inside a freshly started guest — a stop sent right after a start
        # used to fail immediately with "guest agent is not connected"
        # (2026-09-15). So: idempotent if already off, then wait up to 90s for
        # the agent before asking. If the agent still is not there, say so and
        # let the caller retry — deliberately NOT falling back to destroy: a
        # hard kill mid-boot is how arcade2's card once ended up in D3cold.
        $V domstate "$vm" 2>/dev/null | grep -q running \
          || { echo "$vm is not running, nothing to stop"; exit 0; }
        for _ in $(seq 30); do
          $V qemu-agent-command "$vm" '{"execute":"guest-ping"}' >/dev/null 2>&1 && break
          sleep 3
        done
        if ! $V shutdown --mode agent "$vm"; then
          echo "guest agent still not up after 90s — $vm is likely mid-boot; retry in a minute"
          exit 1
        fi
        ;;
      status) exec $V domstate "$vm" ;;
      *) echo "denied: bad action"; exit 1 ;;
    esac
  '';
in
{
  imports = [
    ./hardware-configuration.nix
    ../../modules/private-ca.nix
    # On-demand k3s agent (see the header). Contributes CPU/RAM to the cluster
    # while the arcade VMs are shut down; drained before a gaming session.
    ../../modules/k3s-agent.nix
    # Replaces the old PowerShell NUT client at C:\Scripts\nut-monitor.ps1.
    # gaming-01 is on the rolling rack's CyberPower LX1500GU, whose USB cable
    # goes into gpu-01 — so gaming-01 is an upsmon SECONDARY of gpu-01, exactly like
    # gpu-02 and srv-01. POST-INSTALL STEP: seed
    # /var/lib/nut/monclient-password byte-identically to gpu-01's copy, or
    # upsmon refuses to start (which is the failure mode we want).
    ../../modules/ups-client.nix
  ];

  # GRUB, not systemd-boot, and installed for BOTH firmware modes on purpose.
  # gaming-01 is being converted with its firmware stuck in legacy/CSM mode
  # (Load Optimized Defaults on 2026-08-17 flipped it, and BIOS Setup is
  # unreachable — GPU owns video, AMI Setup does not render over SOL). The
  # booted installer confirmed legacy (/sys/firmware/efi absent). Which mode
  # the firmware is in cannot be seen or changed remotely, so the installed
  # system must boot either way:
  #   - device set to the real disk → GRUB embeds core.img in the EF02
  #     bios_grub partition (disko-config.nix) for the legacy/CSM path;
  #   - efiSupport + efiInstallAsRemovable → GRUB also writes the UEFI loader
  #     to the ESP's removable fallback (EFI/BOOT/BOOTX64.EFI), which the
  #     firmware boots WITHOUT an NVRAM entry — important because NVRAM boot
  #     vars are unwritable from a legacy-booted installer (no efivars) and
  #     Load Optimized Defaults likely cleared them anyway.
  # canTouchEfiVariables MUST be false with efiInstallAsRemovable.
  # REVISIT once the firmware is put back to UEFI on a physical visit: this
  # can revert to plain systemd-boot like gpu-01, though there is no need to.
  boot.loader.systemd-boot.enable = false;
  boot.loader.grub = {
    enable = true;
    efiSupport = true;
    efiInstallAsRemovable = true;
    device = "/dev/disk/by-id/nvme-EXAMPLE_NVME_0000000000000001";
    # Mirror the GRUB menu onto the BMC's SOL port (serial unit 1 = COM2, the
    # port the installer's POST output proved is bridged to SOL). This host is
    # headless — the onboard VGA is disabled in BIOS — so without this a failed
    # boot after the vfio change could not be recovered: there would be no way
    # to pick the previous generation. With it, `ipmitool ... sol activate`
    # shows the menu. --append keeps the graphical terminal too.
    extraConfig = ''
      serial --unit=1 --speed=115200 --word=8 --parity=no --stop=1
      terminal_input --append serial
      terminal_output --append serial
    '';
  };
  # Give the menu enough time to catch over a serial link before it auto-boots
  # the (default = newest) generation.
  boot.loader.timeout = lib.mkForce 8;
  boot.loader.efi.canTouchEfiVariables = false;
  boot.loader.efi.efiSysMountPoint = "/boot";

  # IOMMU + VFIO. Both slots verified to hold ONLY their card and that card's
  # audio function — clean isolation, no ACS override needed. Every address
  # and id below was READ OFF THE LIVE HOST, never guessed: an early comment
  # here guessed 2504 for the 3060 when it was really 2503, and the 3050 was
  # documented at 17:00.0 long after it had actually moved to b4:00.0.
  #
  #   0000:65:00.0  10de:2507  RTX 3050 (GA106)      -> arcade1   [vfio]
  #   0000:65:00.1  10de:228e  its HDMI audio                     [vfio]
  #   0000:b4:00.0  10de:2584  RTX 3050 6GB (GA107)  -> arcade2   [vfio]
  #   0000:b4:00.1  10de:2291  its HDMI audio                     [vfio]
  #   0000:17:00.0  10de:1401  GTX 960 (GM206)       -> vm-03   [vfio]
  #   0000:17:00.1  10de:0fba  its HDMI audio                     [vfio]
  #
  # Group 7 (17:00.x) and group 5 (65:00.x) each verified to hold ONLY that
  # card and its audio function, so both are safe to pass through.
  #
  # 2026-09-11: the RTX 3060 that used to sit at 65:00.0 (10de:2503 + audio
  # 228e) moved to gpu-01 as a third general-purpose GPU, and the GTX 960 took
  # its slot as a stopgap for arcade1.
  #
  # 2026-09-14: a second RTX 3050 went into 65:00.0 and the GTX 960 moved to
  # 17:00.0. Read off the live host, and the reading paid for itself: the two
  # 3050s are NOT the same part. arcade1's new card is a GA106 die reporting
  # 10de:2507, with a GA106 audio function — 228e, the same audio id the old
  # 3060 used, which is why 228e is back in the list. arcade2's card is a GA107
  # 6GB reporting 10de:2584. Assuming "a 3050 is a 3050" would have left 2584
  # alone in the list, bound arcade2's card twice over and arcade1's not at all.
  #
  # The GTX 960's ids are now DELIBERATELY ABSENT below: the card stays with
  # the host so k3s can schedule GPU work on it (see the NVIDIA block further
  # down). What frees it is dropping 1401/0fba from this list, NOT the fact
  # that it changed slot — binding is by id, so vfio would have followed the
  # card to 17:00.0 and swallowed it there just the same.
  #
  # vfio-pci.ids binds all four at initrd time (vfio_pci is in
  # boot.initrd.kernelModules below), so nouveau never touches the card.
  # Note this list is belt-and-braces rather than load-bearing: the domains'
  # <hostdev managed='yes'> makes libvirt do the unbind/bind itself at VM
  # start, which is why arcade1 could run on the 960 before this landed.
  #
  # console=ttyS1: this host is HEADLESS. The onboard ASPEED VGA is disabled
  # in BIOS (not enumerated on the PCI bus — confirmed 2026-08-17), so once
  # the cards go to vfio there is no local framebuffer and iKVM stays black
  # until a physical BIOS visit sets Primary Display=Onboard. A serial console
  # on the BMC's SOL port (ttyS1) is the stand-in: unlike AMI Setup, a Linux
  # serial console renders fully over SOL, so `ipmitool ... sol activate`
  # gives a real login. NixOS auto-starts serial-getty@ttyS1 from this param.
  boot.kernelParams = [
    "intel_iommu=on" "iommu=pt"
    "vfio-pci.ids=10de:2507,10de:228e,10de:2584,10de:2291,10de:1401,10de:0fba"
    "console=tty0" "console=ttyS1,115200n8"
  ];

  networking.hostName = "gaming-01";
  networking.useNetworkd = true;
  networking.useDHCP = false;

  # Networking mirrors gpu-01's exactly, including the macvlan indirection.
  # WHY THE MACVLANS: this is a libvirt host, and any future guest that takes
  # a macvtap on the uplink (the gaming guests, most likely) cannot reach the
  # host stack over its own parent interface — a kernel property, not a
  # firewall or routing bug. So gaming-01's own addresses live on macvlans over
  # the parents rather than on the parents themselves, pre-emptively, exactly
  # as gpu-01 and srv-01 do (they learned it the hard way). The fix is needed
  # once per parent interface a guest has a macvtap on, hence both sides.
  # (Originally set up for vm-03's return as a guest. vm-03 was dropped
  # from the fleet in between and came back on 2026-09-14 as the GPU node, so
  # this macvlan pattern is load-bearing again — for it and for the gaming
  # guests both.)
  systemd.network = {
    enable = true;

    netdevs."10-vlan10" = {
      netdevConfig = { Name = "vlan10"; Kind = "vlan"; };
      vlanConfig.Id = 10;
    };
    netdevs."15-mvhost" = {
      netdevConfig = { Name = "mvhost"; Kind = "macvlan"; };
      macvlanConfig.Mode = "bridge";
    };
    netdevs."16-mvhost50" = {
      netdevConfig = { Name = "mvhost50"; Kind = "macvlan"; };
      macvlanConfig.Mode = "bridge";
    };

    # Untagged = VLAN50, tagged VLAN10 rides on top. NB: the interface name
    # is gpu-01's; if the install shows gaming-01 naming its uplink differently,
    # this is the one line to correct.
    networks."10-eno2" = {
      matchConfig.Name = "eno2";
      vlan = [ "vlan10" ];
      macvlan = [ "mvhost50" ];
      networkConfig.DHCP = "no";
      linkConfig.RequiredForOnline = "no";
    };
    # VLAN50 address: address ONLY, deliberately no gateway. The dual-homing
    # rule — exactly one default route per host and it is always the VLAN10
    # one. Two default routes is the most-repeated bug class in this lab.
    networks."25-mvhost50" = {
      matchConfig.Name = "mvhost50";
      address = [ "203.0.113.140/23" ];
      networkConfig.DHCP = "no";
      linkConfig.RequiredForOnline = "no";
    };
    # vlan10 parents the macvlan and brings the link up — no IP here.
    networks."20-vlan10" = {
      matchConfig.Name = "vlan10";
      macvlan = [ "mvhost" ];
      networkConfig.DHCP = "no";
      linkConfig.RequiredForOnline = "no";
    };
    # The real host address. hex(140) = 0x8c, per the VLAN10 IPv6 convention.
    networks."30-mvhost" = {
      matchConfig.Name = "mvhost";
      address = [
        "192.0.2.140/23"
        "2001:db8:50:a::8c/64"
      ];
      routes = [ { Gateway = "192.0.2.254"; } ];
      networkConfig = { DHCP = "no"; DNS = "192.0.2.254"; IPv6AcceptRA = true; };
      domains = [ "lab.example" "example.com" "~." ];
    };
  };
  networking.search = [ "lab.example" "example.com" ];

  # k3s agent: advertise the VLAN10 address as the node IP, same as every other
  # host (the module handles server address, token, firewall). No node taint —
  # the game-mode drain, not the scheduler, is what keeps a gaming session
  # clear of pods. No gpu=nvidia label: it was added 2026-09-14 alongside a host
  # NVIDIA driver for the GTX 960 and removed with it the same day (see the GPU
  # block below) — this node has no GPU the kubelet can offer.
  services.k3s.extraFlags = [ "--node-ip=192.0.2.140" ];

  # GAME MODE: automatically drain gaming-01 off k3s while a gaming VM runs, and
  # return it to the pool when none is. This is a libvirt qemu hook, so it
  # fires no matter HOW the VM is started (Home Assistant button, `virsh
  # start`, autostart) — the on/off surface stays a dumb start/stop.
  #   - prepare (before the VM grabs RAM): cordon + drain gaming-01, so k3s pods
  #     move off it first and can't OOM against the 16 GB guest. Fast today
  #     since gaming-01 only carries DaemonSets (nothing evictable), but stays
  #     correct if the scheduler ever packs it.
  #   - release (VM stopped): if no OTHER arcade VM is still running, uncordon.
  # Uses the seeded admin kubeconfig. Re-entrancy-safe: it checks for the other
  # guest via pgrep, never by calling back into libvirt from inside the hook.
  #
  # Also forces the BMC fan mode to Full Speed while a gaming VM runs. Found
  # 2026-09-02: the passed-through GPUs sit behind vfio-pci, invisible to the
  # board's own thermal zones, so the case fan curve never reacts to them —
  # the RTX 3050 was hitting 86-87C (SW Thermal Slowdown active) with the
  # only reporting case fan (FAN4) sitting at ~800 RPM under Optimal mode.
  # No room to add a dedicated fan for that slot, so brute-force the case
  # airflow instead: raw `0x30 0x45 0x01 <mode>` is the standard Supermicro
  # X9/X10/X11 fan-mode command (00=Standard 01=Full Speed 02=Optimal
  # 04=Heavy IO); verified in-band via ipmitool, FAN4 800->1700 RPM on 01.
  # Revert to Optimal (not Standard) on release to match what was observed
  # as the board's own idle default.
  virtualisation.libvirtd.hooks.qemu.gamemode = pkgs.writeShellScript "gamemode-qemu-hook" ''
    export PATH=/run/current-system/sw/bin:$PATH
    GUEST="$1"; OP="$2"
    case "$GUEST" in arcade1|arcade2) ;; *) exit 0 ;; esac
    K="k3s kubectl --kubeconfig=/etc/rancher/k3s/admin.yaml"
    IPMI="${pkgs.ipmitool}/bin/ipmitool raw 0x30 0x45 0x01"
    OTHER=$([ "$GUEST" = arcade1 ] && echo arcade2 || echo arcade1)
    case "$OP" in
      prepare)
        logger -t gamemode "$GUEST starting -> stop vm-03, cordon+drain gaming-01, BMC fans full speed"
        # vm-03 is the GPU node, a VM on THIS host. Stop it rather than just
        # cordon it: cordoning stops new pods but leaves 4 vCPU and 8 GiB
        # committed, and this box has only 6 cores. Its GPU is the GTX 960 and
        # the arcade guests use other cards, so this is about CPU, not about
        # the passthrough.
        #
        # The drain is synchronous (kubectl only, no libvirt involved) but the
        # virsh calls are fired through systemd-run --no-block ON PURPOSE:
        # calling back into libvirtd from inside its own qemu hook can block,
        # because the hook runs while libvirtd holds locks for the domain being
        # started. A wedged hook would mean an arcade VM that never boots — a
        # far worse failure than vm-03 taking a few extra seconds to go.
        # Ordering is not critical: 62 GiB means no RAM race, only CPU.
        $K drain vm-03 --ignore-daemonsets --delete-emptydir-data --force --timeout=60s 2>&1 | logger -t gamemode
        # No fixed --unit name: a transient unit can outlive its run (notably
        # after a failure) and then systemd-run refuses the SAME name with
        # "already loaded or has a fragment file" — which is exactly how the
        # release branch silently failed to restart vm-03 on 2026-09-15.
        # Auto-generated names collide with nothing; --collect garbage-collects
        # the unit even if it fails.
        systemd-run --no-block --collect \
          ${stopWorker5} 2>&1 | logger -t gamemode
        $K cordon gaming-01 2>&1 | logger -t gamemode
        $K drain gaming-01 --ignore-daemonsets --delete-emptydir-data --force --timeout=120s 2>&1 | logger -t gamemode
        $IPMI 0x01 2>&1 | logger -t gamemode
        ;;
      release)
        if ! pgrep -f "guest=$OTHER," >/dev/null 2>&1; then
          logger -t gamemode "$GUEST stopped, no arcade running -> uncordon gaming-01, start vm-03, BMC fans optimal"
          $K uncordon gaming-01 2>&1 | logger -t gamemode
          $IPMI 0x02 2>&1 | logger -t gamemode
          # The drain's cordon SURVIVES the reboot: the node object is never
          # deleted, so nothing clears spec.unschedulable on its own — after a
          # gaming session vm-03 came back Ready,SchedulingDisabled and would
          # have taken nothing but DaemonSets forever (seen 2026-09-15). The
          # uncordon targets the node OBJECT, so it works even before the VM
          # is up; the kubelet reconnects into an already-schedulable node.
          $K uncordon vm-03 2>&1 | logger -t gamemode
          systemd-run --no-block --collect \
            ${pkgs.libvirt}/bin/virsh start vm-03 2>&1 | logger -t gamemode
        fi
        ;;
    esac
    exit 0
  '';

  users.users.ludorl82 = {
    isNormalUser = true;
    extraGroups = [ "wheel" "libvirtd" ];
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDUMMYDUMMYDUMMYDUMMYDUMMYDUMMYDUMMYDUMMY0000 reader@example"
      # Home Assistant's arcade on/off key — forced to arcadeCtl, nothing else.
      ''command="${arcadeCtl}",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDUMMYDUMMYDUMMYDUMMYDUMMYDUMMYDUMMYDUMMY0000 reader@example''
    ];
  };
  security.sudo.wheelNeedsPassword = false;
  services.openssh.enable = true;

  # libvirt/qemu-kvm host: the gaming guests land here once the second GPU
  # moves across. OVMF/UEFI firmware ships by default, which the Windows
  # guests will need. NOTE: on this host the virt-secret encryption key must
  # be created with the systemd HOST key, not the TPM — Load Optimized
  # Defaults (2026-08-17) left the onboard TPM2 throwing on Esys_CreatePrimary,
  # so `virt-secret-init-encryption` (which uses --with-key=auto → TPM first)
  # SIGABRTs under its sandbox on a fresh key. The key was seeded by hand with
  # --with-key=host during the install; if it is ever regenerated, do the same
  # until the TPM is cleared/re-enabled on a physical BIOS visit.
  virtualisation.libvirtd.enable = true;

  # Binding by `ids=` (not per-PCI-address driver_override) is deliberate: it
  # survives a card moving slot, which is exactly what happened on 2026-09-14.
  # The flip side is that it CANNOT distinguish two identical cards — if a
  # second GA107 3050 ever arrives it will be bound too, wanted or not, and
  # that is the day to switch to driver_override per address.
  boot.initrd.kernelModules = [ "vfio_pci" "vfio" "vfio_iommu_type1" ];
  boot.blacklistedKernelModules = [ "nouveau" ];

  # --- The GTX 960 is UNBOUND, and the host has no NVIDIA driver -------------
  # REVERTED 2026-09-14, same day it was added. The card is no longer in
  # vfio-pci.ids (so arcade1 gets the new 3050 instead), but giving it to the
  # host for k3s is NOT done: loading the nvidia module deadlocked the kernel
  # ~4 minutes into every boot.
  #
  # What the console showed (photo, boot +247s): a hung-task chain headed by
  # `iptables-restor`, with `bridge` waiting on it and `k3s-agent`, `modprobe`,
  # a udev-worker and a kworker all waiting on `bridge`. `Tainted: P` — the
  # proprietary module was loaded. A wedged modprobe serialises every later
  # module load, so k3s never gets br_netfilter, its iptables rules never land,
  # and CreatePodSandBox times out: the node stays Ready with a healthy kubelet
  # while not a single container can start. That is the misleading part —
  # nothing says "GPU" anywhere in the symptom.
  #
  # NOT yet proven to be nvidia's fault rather than a netfilter/bridge race it
  # merely perturbs; what IS established is that this host had a stable k3s
  # agent before the module was added and deadlocked on the first boot after.
  # There is prior form for nvidia hanging this box — see the arcade2 3050
  # shutdown hang (nvidia-modeset loop, card left in D3cold).
  #
  # Before trying again: bring it up with the module blacklisted at boot and
  # `modprobe nvidia` by hand once k3s has settled, to see whether the order is
  # what matters. If it is revived, the branch is NOT a free choice — the 960
  # is Maxwell (GM206), which NVIDIA moved to legacy at the 580 LTSB
  # (supported to Aug 2028); `stable`/`production` (595) gives it no driver at
  # all and fails silently. `open = false` too: open modules are Turing+.
  #
  # The k3s/CDI half of the recipe was never reached, and is not the suspect.
  # It lives in hosts/gpu-02/configuration.nix if this is picked up again.
  #
  # ABOUT THE LOCAL CONSOLE, and a correction. The screen DID show
  # `gaming-01 login:` on tty1 during the failed boot, but that came from the
  # nvidia driver's framebuffer, NOT from the card being unbound — an earlier
  # version of this comment claimed the latter and was wrong. Checked after the
  # revert: no /dev/fb0, no DRM device, no video module, and the 960 reports
  # `boot_vga: 0`, so the firmware never made it the primary display. The
  # screen is dark again and `console=ttyS1` over SOL remains the only console.
  #
  # Two ways to get a real local console back, neither taken yet:
  #   - un-blacklist nouveau for this card. It is in-tree, drives GM206 well
  #     enough for a console, and cannot fight vfio (the passthrough cards are
  #     claimed by id in the initrd). Cheapest option, one line and a reboot.
  #   - set Primary Display to the 960's slot in BIOS, which would hand over a
  #     UEFI GOP framebuffer and give a console with no driver at all. Needs a
  #     physical visit: SOL shows POST codes only, so this is NOT a change to
  #     attempt blind.

  # pciutils so the next person to touch the GPUs can run lspci without
  # falling back to reading /sys by hand, which is what this change needed.
  environment.systemPackages = [ pkgs.pciutils ];

  # --- LAN/VPN-only VNC access to the arcade VMs ----------------------------
  # Each VM's QEMU VNC lives on gaming-01's localhost with a DYNAMIC display
  # (arcade1 was :0, arcade2 :1). These socket-activated proxies expose them on
  # gaming-01's LAN IP at FIXED ports (arcade1 -> 5901, arcade2 -> 5902) and
  # resolve the live display PER CONNECTION, so a VM restart — these are
  # on-demand — never leaves a stale port. Reachable as gaming-01.lab.example:5901
  # / :5902; the guests also forward their own :5900 here so
  # arcade{1,2}.lab.example:5900 work too. The firewall (below) limits the source
  # to the LAN (VLAN10/50) + WireGuard, IPv4 only — these private addresses are
  # already unreachable from the internet, this is defence in depth.
  systemd.sockets.arcade1-vncproxy = {
    wantedBy = [ "sockets.target" ];
    socketConfig = { ListenStream = "192.0.2.140:5901"; Accept = true; FreeBind = true; };
  };
  systemd.sockets.arcade2-vncproxy = {
    wantedBy = [ "sockets.target" ];
    socketConfig = { ListenStream = "192.0.2.140:5902"; Accept = true; FreeBind = true; };
  };
  systemd.services."arcade1-vncproxy@".serviceConfig = {
    ExecStart = pkgs.writeShellScript "arcade1-vncproxy" ''
      d=$(${pkgs.libvirt}/bin/virsh -c qemu:///system vncdisplay arcade1 2>/dev/null | ${pkgs.gnused}/bin/sed 's/.*://')
      [ -n "$d" ] || exit 1
      exec ${pkgs.socat}/bin/socat - TCP4:127.0.0.1:$((5900 + d))
    '';
    StandardInput = "socket";
    StandardOutput = "socket";
  };
  systemd.services."arcade2-vncproxy@".serviceConfig = {
    ExecStart = pkgs.writeShellScript "arcade2-vncproxy" ''
      d=$(${pkgs.libvirt}/bin/virsh -c qemu:///system vncdisplay arcade2 2>/dev/null | ${pkgs.gnused}/bin/sed 's/.*://')
      [ -n "$d" ] || exit 1
      exec ${pkgs.socat}/bin/socat - TCP4:127.0.0.1:$((5900 + d))
    '';
    StandardInput = "socket";
    StandardOutput = "socket";
  };
  networking.firewall.extraCommands = ''
    # arcade VNC proxies: LAN (VLAN10/50) + VPN (WireGuard + IPsec mobile)
    # sources only, IPv4.
    for net in 192.0.2.0/23 203.0.113.0/23 198.18.0.0/24 198.18.1.0/24; do
      iptables -A nixos-fw -p tcp -s "$net" --dport 5901 -j nixos-fw-accept
      iptables -A nixos-fw -p tcp -s "$net" --dport 5902 -j nixos-fw-accept
    done
  '';

  system.stateVersion = "26.05";
}
